services:
  - type: web
    name: your-playlist-app
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: true
    envVars:
      - key: NODE_VERSION
        value: 18.12.0
    routes:
      - type: rewrite
        source: /*
        destination: /index.html